### ISSUE TITLE
typo?

### ISSUE THREAD

**Issue by moimikey** [perchlayer/webird#3]
https://github.com/perchlayer/webird/blob/master/dev/gulpfile.webpack.coffee#L176

**Comment by dschissler** [comment]
What do you think that the line should be?

**Comment by moimikey** [comment]
mimetype :)On Sun, Jan 25, 2015 at 10:14 PM,  dschissler notifications@github.com wrote:            What do you think that the line should be?

**Comment by dschissler** [comment]
Right.  Sure enough.  I'm catching up on some jet lag and I'll get to it in some hours.

**Comment by dschissler** [comment]
Fixed.
