### ISSUE TITLE
Fix error with incorrect password

### ISSUE THREAD

**Issue by dschissler** [perchlayer/webird#36]
When the incorrect password is entered the error message `"PHP message: Exception: SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'attempted' at row 1"` is logged.

**Comment by andrew-demb** [comment]
Use integer type, or datetime-related from your database (mysql?).
Currently used `smallint` have max value 65535 (unsigned), which is not enough for unix timestamp.

Here
https://github.com/perchlabs/webird/blob/f3f3e2d6612baafc4d245f5cef9523ad5c370717/etc/schema.sql#L109

**Comment by dschissler** [comment]
@andrew-demb Let me know if [this commit](https://github.com/perchlabs/webird/commit/740a5926112e85148c0d28058f42ce1484837aac) fixed it.  I probably will need a week to verify but I'll mark this as solved for now.
